import Head from "next/head";
import React from "react";
import { useState, useEffect } from "react";
import AOS from 'aos';
// import 'animate.css';
import CustomCursor from './cursor.js'
import Navbar from './Navbar.js'
import Hero from "./hero.js";
import Aboutt from "./aboutt.js"
import Contact from "./contact.js"
import Footer from "./footer.js";
import Skills from "./skills.js";
import Experience from "./experience.js";
import Project from "./project.js"


export default function Home() {
  const [darkMode] = useState(true);
  useEffect(() => {
    AOS.init({
    });
  }, []);

    return (
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Anubhav Mendhiratta Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        </Head>
        <main className="back  md:px-20 lg:px-40">
          <CustomCursor />
          <section id="#hero">
            <Navbar />

            <Hero />
          </section>
          <section id="about" >
            <Aboutt />
          </section><br /><br /><br /><br /><br /><br /><br />
          <section  className="logo flex flex-wrap justify-center" id="skills">
            <Skills />
          </section >
          <br /><br /><br /><br /><br /><br /><br /><br />
          <section id="exp">
            <Experience />
          </section>
          <br /><br /><br /><br /><br /><br /><br /><br />
          <section  id="projects">
            <h3 className="fontt animate-pulse text-7xl dark:text-teal-600 text-center">PROJECTS</h3><br /><br /><br /><br />
            <Project />
          </section><br /><br />
          <section  id="contact">
            <Contact />
          </section>
          <section>
            <Footer />
          </section>
        </main>
      </div>
    );
  }